/*
 * GestionUsuarios.java
 *
 * Created on 25 de junio de 2008, 19:58
 */
package ar.com.jpack.desktop.administracion;
// <editor-fold defaultstate="collapsed" desc="Imports">
import ar.com.jpack.desktop.DesktopApp;
import ar.com.jpack.transferencia.UsuariosT;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JInternalFrame;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeSelectionModel;
import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
// </editor-fold>
/**
 * InternalFrame para la gestion de los usuarios.
 * @author  jmhanun
 */
public class GestionUsuarios extends JInternalFrame {

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuariosT = new ar.com.jpack.transferencia.UsuariosT();
        jSplitPane = new javax.swing.JSplitPane();
        izqPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();
        derPanel = new javax.swing.JPanel();
        nuevoButton = new javax.swing.JButton();
        tabPanel = new javax.swing.JTabbedPane();
        datosPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        usuarioTextField = new javax.swing.JTextField();
        nombresTextField = new javax.swing.JTextField();
        apellidosTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        estadoTextField = new javax.swing.JTextField();
        contrasenaPasswordField = new javax.swing.JPasswordField();
        grabarButton = new javax.swing.JButton();
        rolesPanel = new javax.swing.JPanel();
        deshabilitarToggleButton = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.com.jpack.desktop.DesktopApp.class).getContext().getResourceMap(GestionUsuarios.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jSplitPane.setDividerLocation(125);
        jSplitPane.setName("jSplitPane"); // NOI18N

        izqPanel.setName("izqPanel"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTree.setName("jTree"); // NOI18N
        jTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree);

        javax.swing.GroupLayout izqPanelLayout = new javax.swing.GroupLayout(izqPanel);
        izqPanel.setLayout(izqPanelLayout);
        izqPanelLayout.setHorizontalGroup(
            izqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        izqPanelLayout.setVerticalGroup(
            izqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
        );

        jSplitPane.setLeftComponent(izqPanel);

        derPanel.setName("derPanel"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(ar.com.jpack.desktop.DesktopApp.class).getContext().getActionMap(GestionUsuarios.class, this);
        nuevoButton.setAction(actionMap.get("nuevoUsuario")); // NOI18N
        nuevoButton.setText(resourceMap.getString("nuevoButton.text")); // NOI18N
        nuevoButton.setName("nuevoButton"); // NOI18N

        tabPanel.setName("tabPanel"); // NOI18N

        datosPanel.setName("datosPanel"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        usuarioTextField.setEnabled(false);
        usuarioTextField.setName("usuarioTextField"); // NOI18N
        usuarioTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usuarioTextFieldKeyTyped(evt);
            }
        });

        nombresTextField.setName("nombresTextField"); // NOI18N
        nombresTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombresTextFieldKeyTyped(evt);
            }
        });

        apellidosTextField.setName("apellidosTextField"); // NOI18N
        apellidosTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidosTextFieldKeyTyped(evt);
            }
        });

        emailTextField.setName("emailTextField"); // NOI18N
        emailTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailTextFieldKeyTyped(evt);
            }
        });

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        estadoTextField.setEnabled(false);
        estadoTextField.setName("estadoTextField"); // NOI18N

        contrasenaPasswordField.setEnabled(false);
        contrasenaPasswordField.setName("contrasenaPasswordField"); // NOI18N
        contrasenaPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contrasenaPasswordFieldKeyTyped(evt);
            }
        });

        grabarButton.setAction(actionMap.get("grabarUsuario")); // NOI18N
        grabarButton.setName("grabarButton"); // NOI18N

        javax.swing.GroupLayout datosPanelLayout = new javax.swing.GroupLayout(datosPanel);
        datosPanel.setLayout(datosPanelLayout);
        datosPanelLayout.setHorizontalGroup(
            datosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(datosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(contrasenaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombresTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTextField)
                    .addComponent(apellidosTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(estadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosPanelLayout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(grabarButton)
                .addContainerGap())
        );

        datosPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {apellidosTextField, contrasenaPasswordField, emailTextField, estadoTextField, nombresTextField, usuarioTextField});

        datosPanelLayout.setVerticalGroup(
            datosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(datosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contrasenaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(datosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombresTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(datosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(datosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(datosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grabarButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPanel.addTab(resourceMap.getString("datosPanel.TabConstraints.tabTitle"), datosPanel); // NOI18N

        rolesPanel.setName("rolesPanel"); // NOI18N

        javax.swing.GroupLayout rolesPanelLayout = new javax.swing.GroupLayout(rolesPanel);
        rolesPanel.setLayout(rolesPanelLayout);
        rolesPanelLayout.setHorizontalGroup(
            rolesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );
        rolesPanelLayout.setVerticalGroup(
            rolesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        tabPanel.addTab(resourceMap.getString("rolesPanel.TabConstraints.tabTitle"), rolesPanel); // NOI18N

        deshabilitarToggleButton.setAction(actionMap.get("deshabilitarUsuario")); // NOI18N
        deshabilitarToggleButton.setText(resourceMap.getString("deshabilitarToggleButton.text")); // NOI18N
        deshabilitarToggleButton.setName("deshabilitarToggleButton"); // NOI18N

        javax.swing.GroupLayout derPanelLayout = new javax.swing.GroupLayout(derPanel);
        derPanel.setLayout(derPanelLayout);
        derPanelLayout.setHorizontalGroup(
            derPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, derPanelLayout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addComponent(nuevoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deshabilitarToggleButton)
                .addContainerGap())
        );

        derPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {deshabilitarToggleButton, nuevoButton});

        derPanelLayout.setVerticalGroup(
            derPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, derPanelLayout.createSequentialGroup()
                .addComponent(tabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(derPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deshabilitarToggleButton)
                    .addComponent(nuevoButton))
                .addContainerGap())
        );

        jSplitPane.setRightComponent(derPanel);

        getContentPane().add(jSplitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTreeValueChanged
    //Returns the last path element of the selection.
    //This method is useful only when the selection model allows a single selection.
    //Cada vez que haya un cambio en el valor seleccionado del arbol,
    //la variable usuariosT se actualiza.
    DefaultMutableTreeNode node = (DefaultMutableTreeNode) jTree.getLastSelectedPathComponent();
    if (node == null) {
        usuariosT = new UsuariosT();
    } else {
        if (node.getUserObject() instanceof UsuariosT) {
            usuariosT = (UsuariosT) node.getUserObject();
        } else {
            usuariosT = new UsuariosT();
        }
    }
    grabarButton.setEnabled(false);
    usuarioTextField.setEnabled(false);
    contrasenaPasswordField.setEnabled(false);
    cargar();
}//GEN-LAST:event_jTreeValueChanged

private void usuarioTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioTextFieldKeyTyped
    usuariosT.setUsuario(usuarioTextField.getText() + String.valueOf(evt.getKeyChar()));
    grabarButton.setEnabled(true);
}//GEN-LAST:event_usuarioTextFieldKeyTyped

private void contrasenaPasswordFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contrasenaPasswordFieldKeyTyped
    usuariosT.setContrasena(contrasenaPasswordField.getText() + String.valueOf(evt.getKeyChar()));
    grabarButton.setEnabled(true);
}//GEN-LAST:event_contrasenaPasswordFieldKeyTyped

private void nombresTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresTextFieldKeyTyped
    usuariosT.setNombres(nombresTextField.getText() + String.valueOf(evt.getKeyChar()));
    grabarButton.setEnabled(true);
}//GEN-LAST:event_nombresTextFieldKeyTyped

private void apellidosTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidosTextFieldKeyTyped
    usuariosT.setApellidos(apellidosTextField.getText() + String.valueOf(evt.getKeyChar()));
    grabarButton.setEnabled(true);
}//GEN-LAST:event_apellidosTextFieldKeyTyped

private void emailTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTextFieldKeyTyped
    usuariosT.setMails(emailTextField.getText() + String.valueOf(evt.getKeyChar()));
    grabarButton.setEnabled(true);
}//GEN-LAST:event_emailTextFieldKeyTyped
    //<editor-fold defaultstate="collapsed" desc="Declaracion de variables">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidosTextField;
    private javax.swing.JPasswordField contrasenaPasswordField;
    private javax.swing.JPanel datosPanel;
    private javax.swing.JPanel derPanel;
    private javax.swing.JToggleButton deshabilitarToggleButton;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField estadoTextField;
    private javax.swing.JButton grabarButton;
    private javax.swing.JPanel izqPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JTree jTree;
    private javax.swing.JTextField nombresTextField;
    private javax.swing.JButton nuevoButton;
    private javax.swing.JPanel rolesPanel;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JTextField usuarioTextField;
    private ar.com.jpack.transferencia.UsuariosT usuariosT;
    // End of variables declaration//GEN-END:variables
    private static GestionUsuarios gestionUsuarios = new GestionUsuarios();
//</editor-fold>
    /** Creates new form GestionUsuarios */
    private GestionUsuarios() {
        initComponents();
        iniciar(DesktopApp.getApplication().getUsuarioLogueado());

    }

    public static GestionUsuarios getGestionUsuarios() {
        return gestionUsuarios;

    }

    private void iniciar(UsuariosT usu) {
        ResourceMap resourceMap = DesktopApp.getApplication().getContext().getResourceMap(GestionUsuarios.class);
        ArrayList<UsuariosT> usuariosTs = (ArrayList<UsuariosT>) DesktopApp.getApplication().getAllUsuarios();
        DefaultMutableTreeNode padre = new DefaultMutableTreeNode(resourceMap.getString("usuarios"));
        int index = -1;
        int iteration = 0;
        for (Iterator<UsuariosT> it = usuariosTs.iterator(); it.hasNext();) {
            UsuariosT usuario = it.next();
            if (usu != null) {
                if (usu.toString().equals(usuario.toString())) {
                    index = iteration + 1;
                }
            }
            DefaultMutableTreeNode hijo = new DefaultMutableTreeNode(usuario);
            padre.add(hijo);
            iteration++;
        }
        jTree.setModel(new DefaultTreeModel(padre));
        jTree.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        jTree.setSelectionRow(index);
    }

    private void cargar() {
        this.apellidosTextField.setText(usuariosT.getApellidos());
        this.contrasenaPasswordField.setText(usuariosT.getContrasena());
        this.emailTextField.setText(usuariosT.getMails());
        this.estadoTextField.setText(usuariosT.getIdEstado() != null ? usuariosT.getIdEstado().getDescripcion() : "");
        this.nombresTextField.setText(usuariosT.getNombres());
        this.usuarioTextField.setText(usuariosT.getUsuario());
        if (usuariosT.getIdEstado() != null) {
            this.deshabilitarToggleButton.setSelected(usuariosT.getIdEstado().getIdEstado() == 1 ? false : true);
        } else {
            this.deshabilitarToggleButton.setSelected(false);
        }
    }

    @Action
    public void grabarUsuario() {
        usuariosT = DesktopApp.getApplication().grabarUsuarioT(usuariosT);
        cargar();
        iniciar(usuariosT);
        DesktopApp.getApplication().getDesktopView().setStatusMessage("Cambios aplicados");
    }

    @Action
    public void nuevoUsuario() {
        jTree.setSelectionRow(-1);
        grabarButton.setEnabled(true);
        usuarioTextField.setEnabled(true);
        contrasenaPasswordField.setEnabled(true);
    }

    @Action
    public void deshabilitarUsuario() {
        if (usuariosT.getIdEstado().getIdEstado() == 1) {
            usuariosT.getIdEstado().setIdEstado(3);
        } else {
            usuariosT.getIdEstado().setIdEstado(1);
        }
        grabarUsuario();
    }
}