/*
 * GestionUsuarios.java
 *
 * Created on 25 de junio de 2008, 19:58
 */
package ar.com.jpack.desktop.administracion;

import javax.swing.JInternalFrame;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 * InternalFrame para la gestion de los usuarios.
 * @author  jmhanun
 */
public class GestionUsuarios extends JInternalFrame {

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        izqPanel = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();
        derPanel = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.com.jpack.desktop.DesktopApp.class).getContext().getResourceMap(GestionUsuarios.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jSplitPane.setDividerLocation(125);
        jSplitPane.setName("jSplitPane"); // NOI18N

        izqPanel.setName("izqPanel"); // NOI18N

        jScrollPane.setName("jScrollPane"); // NOI18N

        jTree.setModel(null);
        jTree.setName("jTree"); // NOI18N
        jTree.setSelectionModel(null);
        jScrollPane.setViewportView(jTree);

        javax.swing.GroupLayout izqPanelLayout = new javax.swing.GroupLayout(izqPanel);
        izqPanel.setLayout(izqPanelLayout);
        izqPanelLayout.setHorizontalGroup(
            izqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        izqPanelLayout.setVerticalGroup(
            izqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
        );

        jSplitPane.setLeftComponent(izqPanel);

        derPanel.setName("derPanel"); // NOI18N

        javax.swing.GroupLayout derPanelLayout = new javax.swing.GroupLayout(derPanel);
        derPanel.setLayout(derPanelLayout);
        derPanelLayout.setHorizontalGroup(
            derPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );
        derPanelLayout.setVerticalGroup(
            derPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        jSplitPane.setRightComponent(derPanel);

        getContentPane().add(jSplitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel derPanel;
    private javax.swing.JPanel izqPanel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JTree jTree;
    // End of variables declaration//GEN-END:variables
    private static GestionUsuarios gestionUsuarios = new GestionUsuarios();

    /** Creates new form GestionUsuarios */
    private GestionUsuarios() {
        initComponents();
        DefaultMutableTreeNode padre = new DefaultMutableTreeNode(new Integer(3));
        DefaultMutableTreeNode hijo1 = new DefaultMutableTreeNode("hijo1");
        DefaultMutableTreeNode hijo2 = new DefaultMutableTreeNode("hijo2");
        DefaultMutableTreeNode nieto1 = new DefaultMutableTreeNode(new Float(2.2));
        DefaultTreeModel modelo = new DefaultTreeModel(padre);
        modelo.insertNodeInto(hijo1, padre, 0);
        modelo.insertNodeInto(hijo2, padre, 1);
        modelo.insertNodeInto(nieto1, hijo1, 0);
        jTree.setModel(modelo);

    }

    public static GestionUsuarios getGestionUsuarios() {
        return gestionUsuarios;
    }
}