/*
 * Articulos.java
 *
 * Created on 4 de agosto de 2008, 15:41
 */
package ar.com.jpack.desktop.lov;

import ar.com.jpack.desktop.DesktopApp;
import ar.com.jpack.desktop.DesktopView;
import ar.com.jpack.transferencia.ArticulosT;
import ar.com.jpack.helpers.LOVHelper;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;
import org.jdesktop.beansbinding.Binding;

/**
 *
 * @author  jmhanun
 */
public class Articulos extends javax.swing.JDialog {

    /** Creates new form Articulos */
    public Articulos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        articulosTable.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        articulosTable.getSelectionModel().addListSelectionListener(
                new ListSelectionListener() {

                    public void valueChanged(ListSelectionEvent e) {
                        aceptarButton.setEnabled(articulosTable.getSelectedRow() != -1);
                    }
                });
        getRootPane().setDefaultButton(buscarButton);
    }
    protected ArticulosT articuloTSeleccionado;

    public ArticulosT getArticuloTSeleccionado() {
        return articuloTSeleccionado;
    }

    public void setArticuloTSeleccionado(ArticulosT articuloTSeleccionado) {
        ArticulosT oldArticuloTSeleccionado = this.articuloTSeleccionado;
        this.articuloTSeleccionado = articuloTSeleccionado;
        propertyChangeSupport.firePropertyChange("articuloTSeleccionado", oldArticuloTSeleccionado, articuloTSeleccionado);
    }
    private PropertyChangeSupport propertyChangeSupport = new PropertyChangeSupport(this);

    @Override
    public void addPropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.addPropertyChangeListener(listener);
    }

    @Override
    public void removePropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.removePropertyChangeListener(listener);
    }

    public void limpiar() {
        idArticuloTextField.setText("");
        codigoTextField.setText("");
        descripcionTextField.setText("");
        aceptarButton.setEnabled(false);
        setArticuloTSeleccionado(null);
        if (articulosTs != null) {
            Binding b = LOVHelper.findBinding(bindingGroup, articulosTs, articulosTable);
            b.unbind();

            articulosTs.clear();

            b.bind();

            articulosTable.repaint();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        articulosTs = new java.util.ArrayList<ar.com.jpack.transferencia.ArticulosT>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idArticuloTextField = new javax.swing.JTextField();
        codigoTextField = new javax.swing.JTextField();
        descripcionTextField = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        articulosTable = new javax.swing.JTable();
        cancelarButton = new javax.swing.JButton();
        aceptarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.com.jpack.desktop.DesktopApp.class).getContext().getResourceMap(Articulos.class);
        setTitle(resourceMap.getString("Articulos.title")); // NOI18N
        setName("Articulos"); // NOI18N
        setResizable(false);

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        idArticuloTextField.setText(resourceMap.getString("idArticuloTextField.text")); // NOI18N
        idArticuloTextField.setName("idArticuloTextField"); // NOI18N

        codigoTextField.setText(resourceMap.getString("codigoTextField.text")); // NOI18N
        codigoTextField.setName("codigoTextField"); // NOI18N

        descripcionTextField.setText(resourceMap.getString("descripcionTextField.text")); // NOI18N
        descripcionTextField.setName("descripcionTextField"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(ar.com.jpack.desktop.DesktopApp.class).getContext().getActionMap(Articulos.class, this);
        buscarButton.setAction(actionMap.get("buscarArticulos")); // NOI18N
        buscarButton.setName("buscarButton"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        articulosTable.setName("articulosTable"); // NOI18N

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, articulosTs, articulosTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idArticulo}"));
        columnBinding.setColumnName("Id Articulo");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codigo}"));
        columnBinding.setColumnName("Codigo");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${descripcion}"));
        columnBinding.setColumnName("Descripcion");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(articulosTable);
        articulosTable.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("articulosTable.columnModel.title0")); // NOI18N
        articulosTable.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("articulosTable.columnModel.title1")); // NOI18N
        articulosTable.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("articulosTable.columnModel.title2")); // NOI18N

        cancelarButton.setAction(actionMap.get("cancelar")); // NOI18N
        cancelarButton.setName("cancelarButton"); // NOI18N

        aceptarButton.setAction(actionMap.get("seleccionarArticulo")); // NOI18N
        aceptarButton.setEnabled(false);
        aceptarButton.setName("aceptarButton"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idArticuloTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                            .addComponent(codigoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                            .addComponent(descripcionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)))
                    .addComponent(buscarButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(aceptarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarButton)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {aceptarButton, cancelarButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idArticuloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codigoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(descripcionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton)
                    .addComponent(aceptarButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public Task buscarArticulos() {
        return new BuscarArticulosTask(DesktopApp.getApplication(),"Busqueda Iniciada");
    }

    private class BuscarArticulosTask extends org.jdesktop.application.Task<String, Void> {
        DesktopView view;
        String mensaje;
        BuscarArticulosTask(DesktopApp app, String mensaje) {
            super(app);
            this.view = app.getDesktopView();
            this.mensaje=mensaje;
        }
        @Override protected String doInBackground() {              
            view.setStatusMessage(mensaje);
            if(articulosTs == null){
                articulosTs = new ArrayList<ArticulosT>();
            }
            
            Binding b = LOVHelper.findBinding(bindingGroup, articulosTs, articulosTable);
            b.unbind();

            articulosTs.clear();

            HashMap parametros = new HashMap();
            if (!idArticuloTextField.getText().isEmpty()) {
                try{
                    parametros.put("pIdArticulos", Integer.parseInt(idArticuloTextField.getText()));
                }catch(NumberFormatException ex){
                    JOptionPane.showMessageDialog(rootPane, "El campo id articulo debe ser numerico, se omitira en la busqueda");
                    idArticuloTextField.setText("");
                }
            }
            if (!codigoTextField.getText().isEmpty()) {
                parametros.put("pCodigo", codigoTextField.getText().toUpperCase());
            }
            if (!descripcionTextField.getText().isEmpty()) {
                parametros.put("pDescripcion", descripcionTextField.getText().toUpperCase());
            }
            articulosTs.addAll((ArrayList<ArticulosT>)DesktopApp.getApplication().getArticulosT(parametros));

            b.bind();

            articulosTable.repaint();
            
            int total = articulosTs.size();
            if (total > 1) {
                mensaje = total + " registros encontrados";
            } else if (total == 1) {
                mensaje = total + " registro encontrado";
            } else {
                mensaje = "No se encontraron registros";
            }
            return mensaje;
    }
        @Override protected void succeeded(String result) {
            super.succeeded(result);
            view.setStatusMessage(result);
        }
    }
    
   

    @Action
    public void seleccionarArticulo() {
        setArticuloTSeleccionado(articulosTs.get(articulosTable.getSelectedRow()));
        setVisible(false);
    }

    @Action
    public void cancelar() {
        setArticuloTSeleccionado(null);
        setVisible(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JTable articulosTable;
    private java.util.ArrayList<ar.com.jpack.transferencia.ArticulosT> articulosTs;
    private javax.swing.JButton buscarButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JTextField codigoTextField;
    private javax.swing.JTextField descripcionTextField;
    private javax.swing.JTextField idArticuloTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
