/*
 * UnidadesMedida.java
 *
 * Created on 4 de agosto de 2008, 15:42
 */
package ar.com.jpack.desktop.lov;

import ar.com.jpack.desktop.DesktopApp;
import ar.com.jpack.transferencia.UnidadesMedidaT;
import ar.com.jpack.helpers.LOVHelper;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.jdesktop.application.Action;
import org.jdesktop.beansbinding.Binding;

/**
 *
 * @author  jmhanun
 */
public class UnidadesMedida extends javax.swing.JDialog {

    /** Creates new form UnidadesMedida */
    public UnidadesMedida(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        if (unidadesMedidaTs == null) {
            unidadesMedidaTs = new ArrayList<UnidadesMedidaT>();
        }

        Binding b = LOVHelper.findBinding(bindingGroup, unidadesMedidaTs, unidadesMedidaTable);
        b.unbind();

        unidadesMedidaTs.clear();

        unidadesMedidaTs.addAll((ArrayList<UnidadesMedidaT>) DesktopApp.getApplication().getUnidadesMedida());

        b.bind();

        unidadesMedidaTable.repaint();

        String mensaje;
        
        int total = unidadesMedidaTs.size();
        if (total > 1) {
            mensaje = total + " registros encontrados";
        } else if (total == 1) {
            mensaje = total + " registro encontrado";
        } else {
            mensaje = "No se encontraron registros";
        }
        
        DesktopApp.getApplication().getDesktopView().setStatusMessage(mensaje);

        unidadesMedidaTable.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        unidadesMedidaTable.getSelectionModel().addListSelectionListener(
                new ListSelectionListener() {

                    public void valueChanged(ListSelectionEvent e) {
                        aceptarButton.setEnabled(unidadesMedidaTable.getSelectedRow() != -1);
                    }
                });
        getRootPane().setDefaultButton(aceptarButton);
    }
    protected UnidadesMedidaT unidadMedidaTSeleccionado;

    public UnidadesMedidaT getUnidadMedidaTSeleccionado() {
        return unidadMedidaTSeleccionado;
    }

    public void setUnidadMedidaTSeleccionado(UnidadesMedidaT unidadMedidaTSeleccionado) {
        UnidadesMedidaT oldUnidadMedidaTSeleccionado = this.unidadMedidaTSeleccionado;
        this.unidadMedidaTSeleccionado = unidadMedidaTSeleccionado;
        propertyChangeSupport.firePropertyChange("unidadMedidaTSeleccionado", oldUnidadMedidaTSeleccionado, unidadMedidaTSeleccionado);
    }
    private PropertyChangeSupport propertyChangeSupport = new PropertyChangeSupport(this);

    @Override
    public void addPropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.addPropertyChangeListener(listener);
    }

    @Override
    public void removePropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.removePropertyChangeListener(listener);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        unidadesMedidaTs = new java.util.ArrayList<ar.com.jpack.transferencia.UnidadesMedidaT>();
        jScrollPane1 = new javax.swing.JScrollPane();
        unidadesMedidaTable = new javax.swing.JTable();
        cancelarButton = new javax.swing.JButton();
        aceptarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ar.com.jpack.desktop.DesktopApp.class).getContext().getResourceMap(UnidadesMedida.class);
        setTitle(resourceMap.getString("UnidadesMedida.title")); // NOI18N
        setName("UnidadesMedida"); // NOI18N
        setResizable(false);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        unidadesMedidaTable.setName("unidadesMedidaTable"); // NOI18N

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, unidadesMedidaTs, unidadesMedidaTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idUnidMedida}"));
        columnBinding.setColumnName("Id Unid Medida");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${abreviatura}"));
        columnBinding.setColumnName("Abreviatura");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${descripcion}"));
        columnBinding.setColumnName("Descripcion");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(unidadesMedidaTable);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(ar.com.jpack.desktop.DesktopApp.class).getContext().getActionMap(UnidadesMedida.class, this);
        cancelarButton.setAction(actionMap.get("cancelar")); // NOI18N
        cancelarButton.setName("cancelarButton"); // NOI18N

        aceptarButton.setAction(actionMap.get("seleccionarUnidadMedida")); // NOI18N
        aceptarButton.setEnabled(false);
        aceptarButton.setName("aceptarButton"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(246, Short.MAX_VALUE)
                .addComponent(aceptarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelarButton)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {aceptarButton, cancelarButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton)
                    .addComponent(aceptarButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents


    @Action
    public void seleccionarUnidadMedida() {
        setUnidadMedidaTSeleccionado(unidadesMedidaTs.get(unidadesMedidaTable.getSelectedRow()));
        setVisible(false);
    }

    @Action
    public void cancelar() {
        setUnidadMedidaTSeleccionado(null);
        setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable unidadesMedidaTable;
    private java.util.ArrayList<ar.com.jpack.transferencia.UnidadesMedidaT> unidadesMedidaTs;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
