/*
 * ArticulosFrame.java
 *
 * Created on 19 de noviembre de 2007, 23:30
 */
package ar.com.jpack.app.gui;

import ar.com.jpack.app.modelos.ArticulosModelo;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author  Pablo
 */
public class ArticulosFrame extends javax.swing.JInternalFrame {

    /** Creates new form ArticulosFrame */
    public ArticulosFrame() {
        modelo = new ArticulosModelo();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablaScrollPane = new javax.swing.JScrollPane();
        articulosTable = new javax.swing.JTable();
        nuevoArticuloButton = new javax.swing.JButton();
        editarArticuloButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Catalogo de articulos");
        addInternalFrameListener(formListener);

        articulosTable.setModel(modelo.getArticulosTableModel());
        tablaScrollPane.setViewportView(articulosTable);

        nuevoArticuloButton.setText("Nuevo articulo");
        nuevoArticuloButton.addActionListener(formListener);

        editarArticuloButton.setText("Editar articulo");
        editarArticuloButton.addActionListener(formListener);

        salirButton.setText("Salir");
        salirButton.addActionListener(formListener);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nuevoArticuloButton)
                    .addComponent(editarArticuloButton)
                    .addComponent(salirButton))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {editarArticuloButton, nuevoArticuloButton, salirButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nuevoArticuloButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editarArticuloButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(salirButton))
                    .addComponent(tablaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, javax.swing.event.InternalFrameListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == salirButton) {
                ArticulosFrame.this.salirButtonActionPerformed(evt);
            }
            else if (evt.getSource() == nuevoArticuloButton) {
                ArticulosFrame.this.nuevoArticuloButtonActionPerformed(evt);
            }
            else if (evt.getSource() == editarArticuloButton) {
                ArticulosFrame.this.editarArticuloButtonActionPerformed(evt);
            }
        }

        public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            if (evt.getSource() == ArticulosFrame.this) {
                ArticulosFrame.this.formInternalFrameActivated(evt);
            }
        }

        public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
        }

        public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
        }

        public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
        }

        public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
        }

        public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
        }

        public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
        }
    }// </editor-fold>//GEN-END:initComponents

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirButtonActionPerformed

    private void nuevoArticuloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoArticuloButtonActionPerformed
        modelo.nuevoArticulo();
        crearArticuloFrame("Nuevo articulo");
    }//GEN-LAST:event_nuevoArticuloButtonActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        articulosTable.updateUI();
    }//GEN-LAST:event_formInternalFrameActivated

    private void editarArticuloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarArticuloButtonActionPerformed
        if (this.articulosTable.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un articulo");
        } else {
            modelo.editarArticulo(this.articulosTable.getSelectedRow());
            crearArticuloFrame("Editar " + modelo.getArticulo().getDescripcion());
        } 
    }//GEN-LAST:event_editarArticuloButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable articulosTable;
    private javax.swing.JButton editarArticuloButton;
    private javax.swing.JButton nuevoArticuloButton;
    private javax.swing.JButton salirButton;
    private javax.swing.JScrollPane tablaScrollPane;
    // End of variables declaration//GEN-END:variables

    private ArticulosModelo modelo;

    private JInternalFrame verificar() {
        JInternalFrame[] internalFrames = ((JDesktopPane) this.getParent()).getAllFrames();
        JInternalFrame x = null;
        for (int i = 0; i < internalFrames.length; i++) {
            JInternalFrame jInternalFrame = internalFrames[i];
            if (jInternalFrame instanceof ar.com.jpack.app.gui.ArticuloFrame) {
                x = jInternalFrame;
            }
        }
        return x;
    }

    private void crearArticuloFrame(String titulo) {
        JInternalFrame x = verificar();
        if (x != null) {
            ((JDesktopPane) this.getParent()).getDesktopManager().activateFrame(x);
        } else {
            ArticuloFrame rolFrame = new ArticuloFrame(modelo, titulo);
            rolFrame.setVisible(true);
            ((JDesktopPane) this.getParent()).add(rolFrame);
            ((JDesktopPane) this.getParent()).getDesktopManager().activateFrame(rolFrame);
        }
    }
}
